/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service readiness probe
         * @description Simple endpoint to confirm the API is up.
         */
        get: operations["readiness_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_v1_events_get"];
        put?: never;
        /** Create Event */
        post: operations["create_event_api_v1_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["get_event_api_v1_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** EventCreate */
        EventCreate: {
            /**
             * Sport Id
             * Format: uuid
             */
            sport_id: string;
            /** Venue Id */
            venue_id?: string | null;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** @default scheduled */
            status: components["schemas"]["EventStatus"];
            /** Ticket Url */
            ticket_url?: string | null;
            /** Participants */
            participants?: components["schemas"]["EventParticipantCreate"][];
        };
        /** EventParticipantCreate */
        EventParticipantCreate: {
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
            /** @default participant */
            role: components["schemas"]["EventParticipantRole"];
        };
        /** EventParticipantRead */
        EventParticipantRead: {
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
            role: components["schemas"]["EventParticipantRole"];
        };
        /**
         * EventParticipantRole
         * @enum {string}
         */
        EventParticipantRole: "home" | "away" | "participant";
        /** EventRead */
        EventRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Sport Id
             * Format: uuid
             */
            sport_id: string;
            /** Venue Id */
            venue_id: string | null;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            status: components["schemas"]["EventStatus"];
            /** Ticket Url */
            ticket_url: string | null;
            /** Participants */
            participants?: components["schemas"]["EventParticipantRead"][];
        };
        /**
         * EventStatus
         * @enum {string}
         */
        EventStatus: "scheduled" | "live" | "finished" | "cancelled";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * OrderDirection
         * @enum {string}
         */
        OrderDirection: "asc" | "desc";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readiness_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_events_api_v1_events_get: {
        parameters: {
            query?: {
                /** @description Filter by sport UUID */
                sport_id?: string | null;
                /** @description Filter by venue UUID */
                venue_id?: string | null;
                /** @description Filter by event status */
                status?: components["schemas"]["EventStatus"] | null;
                /** @description Filter: start >= date_from (ISO 8601 with tz) */
                date_from?: string | null;
                /** @description Filter: start <= date_to (ISO 8601 with tz) */
                date_to?: string | null;
                /** @description Sort by starts_at */
                order?: components["schemas"]["OrderDirection"];
                /** @description Page number (1-based) */
                page?: number;
                /** @description Items per page */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_event_api_v1_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_api_v1_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
